version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/zookeeper/data'
    networks:
      - sc-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/kafka/data'
    networks:
      - sc-network
    environment:
      - KAFKA_BROKER_ID=
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_PLAINTEXT_LISTENER=yes

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/mongo/data'
    networks:
      - sc-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo_express:
    image: mongo-express
    restart: always
    ports:
      - '8083:8083'
    volumes:
      - 'mongo_express_data:/mongo_express/data'
    networks:
      - sc-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017

volumes:
  kafka_data:
  zookeeper_data:
  mongo_data:
  mongo_express_data:

networks:
  sc-network:
    driver: bridge